[package]
name = "fateful"
version = "0.1.0"
edition = "2021"
authors = ["commonkestrel"]
license = "MIT"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version="1", features = ["attributes"] }
bitflags = "2.4"
clap = { version = "4.4", features = ["derive"] }
clio = { version = "0.3", features = ["clap-parse"] }
env_logger = "0.10.1"
log = "0.4.20"
once_cell = "1.18"
shadow-rs = "0.24"
thiserror = "1"

[build-dependencies]
shadow-rs = "0.24"
